### ISSUE TITLE
`pip install codraft` fails as if dependencies are not followed up

### ISSUE THREAD

**Issue by aanastasiou** [CODRA-Ingenierie-Informatique/CodraFT#1] opened 2022-07-21 14:33 UTC
**Describe the bug**
As per the title, the typical `pip install codraft` fails:

1. Because `numpy` was not found  (install manually)
2. Because `cython` was not found (install manually)
3. Because `guidata` was not found (install manually)

**To Reproduce**

Install CodraFT in a completely fresh virtual environment

**Expected behavior**
Installation of CodraFT proceeds as expected

**Screenshots**

There is nothing exceptional here, except that because I installed the latest versions of the "missing" dependencies, I received a message that the program might behave unexpectedly. I think that if I go back and "respect" the versions that are specified in `setup.cfg`, even that message will go away.

**Installation information**
Virtual environment based on Python 3.10.0 through `pyenv` on Ubuntu 22.04

**Additional context**
I noticed that the `setup.py` does not have an `install_requires` section but details are provided in the setup.cfg. Happy to do a PR based on that but I thought I would check first in case installation does anything else that might break because of this change (?)

**Comment by PierreRaybaut** [comment] 2022-07-25 08:40
Actually, this is a guiqwt Issue:
![test_install_codraft (003)](https://user-images.githubusercontent.com/1311787/180734623-1b81c3bc-b92b-4f16-9944-6742adc3497f.png)
Build dependencies are not defined properly, so build will fail until those dependencies are actually installed.

See this issue:
https://github.com/PierreRaybaut/guiqwt/issues/95

**Comment by PierreRaybaut** [comment] 2022-07-25 11:28
This should now be fixed with `guiqwt` v**4.3.1**

**Comment by PierreRaybaut** [comment] 2022-07-25 11:29
I'm letting the Issue opened until you can confirm that it works for you (thanks!)

**Comment by aanastasiou** [comment] 2022-07-25 14:48
@PierreRaybaut thank you. I just tried from a completely blank environment. I am getting a consistent error as far as `pyqt5` is concerned (have confirmed this twice). I don't know what happened with my previous run, it would be great to have kept screenshots or some other kind of log because, I did not do anything vastly different this time around. I do not get the guiqwt error at all.

The pyqt5 error is as follows:
![image](https://user-images.githubusercontent.com/1336337/180804970-3ed17d79-4ea6-447d-88cc-d3b58c7d0e08.png)


In this screenshot, the stack trace comes from a plain simple `> codraft &` invocation.

**Comment by PierreRaybaut** [comment] 2022-07-25 15:08
Ok, so this issue is closed regarding the original bug report.

Regarding the `pyqt5` issue, this is far less surprising for me that you have to install a Python Qt binding library because `CodraFT` relies on `QtPy`, an abstraction Qt layer which is compatible with `PyQt5`, `PyQt6`, `PySide6`... For this reason, I'm kind of reluctant about requiring `pyqt5` specifically (even though `CodraFT` has only been qualified by `pyqt5`...).

About the "Non-compliant dependencies" message:
That is the expected behavior on non-Windows operating systems because `CodraFT` has been qualified on Windows only (for now). It may changed in the near future. If you click on "Ignore", the message box won't show again.

**Closed by PierreRaybaut** 2022-07-25 15:08 UTC
Labels: bug
